[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
lines_between_sections = true
skip = [".venv", "venv", "deploy", ".git", ".github", "migrations"]
extend_skip = [".md", ".json"]

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
\.git
    | \.gitignore
    | \.github
    | \.venv
    | \.pytest_cache
    | \.deploy
    | ^.*\b(migrations)\b.*$
)/
'''

[tool.pyright]
pythonVersion = '3.11'
include = ["danbi_task"]
exclude = [
    "**/__pycache__",
    "**/.venv/",
    "**/venv/",
    "**/deploy/",
    "**/.git/",
    "**/.github/",
    "**/migrations/",
]
ignore = []
stubPath = ""
reportMissingImports = false
reportMissingTypeStubs = false

[tool.pytest.ini_options]
testpaths = [
    "task/tests",
]
DJANGO_SETTINGS_MODULE = "danbi_task.settings.dev"
addopts = "--reuse-db"
filterwarnings = [
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
]
